# How is switzerland feeling?

### Abstract
The idea of the project is to see how tweets could reveal canton-level happiness. We propose to develop a platform  for estimating happiness in the swiss cantons, which uses Twitter as data source and combines sentiment analysis and visualization techniques in order to provide users and the general public with an interactive interface for data exploration.


### Data Description
Geotagged tweets in the Swiss area collected from Twitter.

### Feasibility and Risks
One of the limitations that we are currently thinking of is the possibility that the geotagged tweets are generated by a small minority of the population, which might lead to a bias in any inference that we will make using this data (representation issues). This will be clear once we get our hands dirty and start looking into the data.

### Deliverables


* Platform for estimating happiness in swiss cantons
* Interactive interface for data exploration.


             
### Note
This is a tentative plan, the Deliverables and the Timeplan might change a little bit as we start working on the project and exploring the data. We will adjust this proposal if we decide to make some changes.
